version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: "mvn-boot-repo"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "130738026255"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Run Test Case
      - mvn install    
      - echo Build started on 'date'
      - echo Building the Docker image...  $IMAGE_REPO_NAME        
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo 'Connect to CodeCov'
      - bash codecov.sh
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the artifact image...
      - mvn deploy
artifacts:
  files:
    - target/*.jar
  name: code-build-artifact-$AWS_REGION-$(date +%Y-%m-%d)