version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: "mvn-boot-repo"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "130738026255"
    CODECOV_TOKEN: "22202c95-2fd4-4797-ad98-f1b1c18dc7bb"
  parameter-store:
    CODECOV_TOKEN: /CodeBuild/CODECOV_TOKEN  

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Run Test Case
      - mvn install    
      - echo Build started on 'date'
      - echo Building the Docker image...  $IMAGE_REPO_NAME        
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo 'Connect to CodeCov'
      - bash codecov.sh
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the artifact image...
      - mvn -s settings.xml deploy
reports:
  arn:aws:codebuild:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:report-group/report-group-name-1:
    files:
      - "**/*"
    base-directory: 'target/tests/reports'
    discard-paths: no
  reportGroupCucumberJson:
    files:
      - 'target/surefire-reports/*.xml'
    discard-paths: yes
    file-format: JunitXml # default is JunitXml      
artifacts:
  files:
    - target/*.jar
  name: code-build-artifact-$AWS_REGION-$(date +%Y-%m-%d)
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - target/*.jar
      discard-paths: yes